# Generated by Django 5.1.2 on 2024-10-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits')], max_length=50, unique=True)),
            ],
        ),
    ]
