# Generated by Django 5.1.2 on 2024-10-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('farmer', 'Farmer'), ('customer', 'Customer')], default='admin', max_length=10),
        ),
    ]
